/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import repository.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class FormRoom extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
//    RoomCRUD_list service;
//    int index;
//    int tag = 0;
    /**
     * Creates new form FormRoom
     */
    public FormRoom() {
        initComponents();
        
//        service = new RoomCRUD();
//        this.view();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        this.setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);

        // Initialize tabel agar tampil
        tableModel = (DefaultTableModel) tabelRoom.getModel();
        String[] columnNames = {"ID", "Type", "Price", "Status"};
        tableModel.setColumnIdentifiers(columnNames);
        updateTable() ;

    }

    //Method insert multi
    private void saveRoom() {
        try {
            int id = Integer.parseInt(txtNoRoom.getText());
            String type = jType.getSelectedItem().toString();
            double price = Double.parseDouble(txtHarga.getText());
//            boolean status = chkStatus.isSelected();

            Room room = new Room(id, type, price);
            boolean success = RoomRepo.insert(room);

            if (success) {
                JOptionPane.showMessageDialog(this, "Room saved successfully!");
                updateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save room.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please check your data.");
        }
    }

    //Method update tabel menampilkanya
    private void updateTable() {
        tableModel.setRowCount(0); // Clear existing rows

        for (Room room : RoomRepo.getAll()) {
            Object[] row = new Object[4];
            row[0] = room.getId();
            row[1] = room.getType();
            row[2] = room.getPrice();
            row[3] = room.Status();
            tableModel.addRow(row);
        }
    }
    
//    public void reset() {
//        nama.setText("");
//        hp.setText("");
//        alamat.setText("");
//        status.setText("");
//        kelas.setText("");
//        tp.setText("");
//        jumlah.setText("");
//        instruktur.setText("");
//    }
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logout = new javax.swing.JButton();
        C_CheckIN = new javax.swing.JButton();
        mangeRoom = new javax.swing.JButton();
        C_CheckOut = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRoom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNoRoom = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jType = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txtHarga = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/logout.png"))); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 11, 110, 40));

        C_CheckIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/Customer Registration & Check IN.png"))); // NOI18N
        C_CheckIN.setText("Customer Check-In");
        C_CheckIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_CheckINActionPerformed(evt);
            }
        });
        getContentPane().add(C_CheckIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 11, 145, 43));

        mangeRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/manage room.png"))); // NOI18N
        mangeRoom.setText("Manage Room");
        mangeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangeRoomActionPerformed(evt);
            }
        });
        getContentPane().add(mangeRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 11, 145, 43));

        C_CheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/Customer Check Out.png"))); // NOI18N
        C_CheckOut.setText("Customer Check-Out");
        C_CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_CheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(C_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 11, 145, 43));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/exit.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(944, 11, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/6479339.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 140, 60));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nomor Kamar", "Type Kamar", "Harga", "Setatus"
            }
        ));
        jScrollPane1.setViewportView(tabelRoom);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 24, -1, 362));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nomor Kamar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 24, -1, 24));

        txtNoRoom.setText("...");
        jPanel1.add(txtNoRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 58, 294, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Type Kamar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 106, -1, 24));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 188, -1, 24));

        jType.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Type Kamar", "Deluxe", "Standard", "Exclusive" }));
        jType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jTypeItemStateChanged(evt);
            }
        });
        jType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypeActionPerformed(evt);
            }
        });
        jPanel1.add(jType, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 136, 191, 34));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Add Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 260, -1, -1));

        txtHarga.setText("...");
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 218, 294, 31));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/admin Home.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 91, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/home.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int keluar = JOptionPane.showConfirmDialog(null, "Anda akan LogOut?", "Question", JOptionPane.YES_NO_OPTION);
        if (keluar == 0) {
            Login1 exit = new Login1();
            exit.setVisible(true);
            this.dispose();
        } else {
            return;

        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int kembali = JOptionPane.showConfirmDialog(null, "Anda akan Kembali?", "Question", JOptionPane.YES_NO_OPTION);
        if (kembali == 0) {
            FormReservasi beck = new FormReservasi();
            beck.setVisible(true);
            this.dispose();
        } else {
            return;

        }
    }//GEN-LAST:event_exitActionPerformed

    private void mangeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangeRoomActionPerformed
        FormReservasi next = new FormReservasi();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mangeRoomActionPerformed

    private void C_CheckINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_CheckINActionPerformed
        FormCustomerIn next = new FormCustomerIn();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_C_CheckINActionPerformed

    private void C_CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_CheckOutActionPerformed
        FromCustomerOut next  =new FromCustomerOut();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_C_CheckOutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveRoom();
        
        //Main Object Method Interface
        RoomRepo Rr = new RoomRepo();
        Rr.ToString();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTypeActionPerformed

    private void jTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jTypeItemStateChanged
        //Main object polimorfisme
        String type = jType.getSelectedItem().toString();
        Deluxe dx = new Deluxe(0, "", 0.0);
        Standard st = new Standard(0, "", 0.0);
        Exclusive ex = new Exclusive(0, "", 0.0);

        if (type == "Deluxe") {
            txtHarga.setText(String.valueOf(dx.getPrice()));
        } else if (type == "Standard") {
            txtHarga.setText(String.valueOf(st.getPrice()));
        } else if (type == "Exclusive") {
            txtHarga.setText(String.valueOf(ex.getPrice()));
        }
    }//GEN-LAST:event_jTypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRoom.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRoom.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRoom.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRoom.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_CheckIN;
    private javax.swing.JButton C_CheckOut;
    private javax.swing.JButton Logout;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jType;
    private javax.swing.JButton mangeRoom;
    private javax.swing.JTable tabelRoom;
    private javax.swing.JLabel txtHarga;
    private java.awt.TextField txtNoRoom;
    // End of variables declaration//GEN-END:variables
}
