/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author hp
 */
public class FormReservasi extends javax.swing.JFrame {

    /**
     * Creates new form FormReservasi
     */
    public FormReservasi() {
        initComponents();
        //Posisi Page
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        this.setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        C_CheckIN = new javax.swing.JButton();
        mangeRoom = new javax.swing.JButton();
        C_CheckOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/exit.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 11, -1, 40));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/logout.png"))); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 11, 102, 40));

        C_CheckIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/Customer Registration & Check IN.png"))); // NOI18N
        C_CheckIN.setText("Customer Check-In");
        C_CheckIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_CheckINActionPerformed(evt);
            }
        });
        getContentPane().add(C_CheckIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 277, -1, 52));

        mangeRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/manage room.png"))); // NOI18N
        mangeRoom.setText("Manage Room");
        mangeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangeRoomActionPerformed(evt);
            }
        });
        getContentPane().add(mangeRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 277, 185, 52));

        C_CheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/Customer Check Out.png"))); // NOI18N
        C_CheckOut.setText("Customer Check-Out");
        C_CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_CheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(C_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 277, 169, 52));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int keluar = JOptionPane.showConfirmDialog(null, "Anda akan LogOut?", "Question", JOptionPane.YES_NO_OPTION);
        if (keluar == 0) {
            Login1 exit = new Login1();
            exit.setVisible(true);
            this.dispose();
        } else {
            return;

        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void mangeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangeRoomActionPerformed
        FormRoom next = new FormRoom();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mangeRoomActionPerformed

    private void C_CheckINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_CheckINActionPerformed
        FormCustomerIn next = new FormCustomerIn();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_C_CheckINActionPerformed

    private void C_CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_CheckOutActionPerformed
        FromCustomerOut next = new FromCustomerOut();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_C_CheckOutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int Exit = JOptionPane.showConfirmDialog(null, "Anda akan Kembali?", "Question", JOptionPane.YES_NO_OPTION);
        if (Exit == 0) {
            System.exit(0);
        } else {
            return;

        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_CheckIN;
    private javax.swing.JButton C_CheckOut;
    private javax.swing.JButton Logout;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mangeRoom;
    // End of variables declaration//GEN-END:variables
}
