/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import repository.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.ERROR;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class FromCustomerOut extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private List<Reservasi> dataComboBoxRoom = new ArrayList<>();

    /**
     * Creates new form FromCustomerOut
     */
    public FromCustomerOut() {
        initComponents();
        initTable();

        //Set Location agar di tengah
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();

        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }

        this.setLocation(
                (screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2);

        updateTable();
    }

    //Method inisialisasi tabe;
    private void initTable() {
        tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(new String[]{"ID Reservasi", "Nama", " Nomer Hp", "Negara", "Alamat", "Gender", "Check-in", "Check-Out", "Room ID", "Type", "Total Bayar"});
        tabelDataGT.setModel(tableModel);
    }

    //kembalikan data tabel;
    public DefaultTableModel getTableModel() {
        return tableModel;
    }

    //Method update tabel untuk menampilkanya
    public void updateTable() {
        tableModel.setRowCount(0); // Clear existing rows
        List<Reservasi> reservasi = ReservasiRepo.getAll();
        if (reservasi != null) {
            for (Reservasi data : reservasi) {
                Guest guest = GuestRepo.getById(data.getGuestId());
                Room room = RoomRepo.getById(data.getRoomId());

                if (guest != null && room != null) {

                    Object[] row = new Object[11];
                    row[0] = data.getId();
                    row[1] = GuestRepo.getById(data.getGuestId()).getName();
                    row[2] = GuestRepo.getById(data.getGuestId()).getContact();
                    row[3] = GuestRepo.getById(data.getGuestId()).getCountry();
                    row[4] = GuestRepo.getById(data.getGuestId()).getAddres();
                    row[5] = GuestRepo.getById(data.getGuestId()).getGender();
                    row[6] = data.getTglCheckin();
                    row[7] = data.getTglCheckout();
                    row[8] = data.getRoomId();
                    row[9] = RoomRepo.getById(data.getRoomId()).getType();
                    row[10] = data.getJumlahBayar();
                    tableModel.addRow(row);
                }

            }
        }
    }
    
    
    //Method Clear text
     private void clearTextFields() {
        txtNama.setText("");
        tglCheckIn.setText("");
        txtLamaInap.setText("");
        txtHarga.setText("");
        txtJumlahPay.setText("");
        txtNo.setText("");
        txtID.setText("");
        tglCheckOut.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        txtNo = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();
        txtNama = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        txtLamaInap = new java.awt.TextField();
        jLabel8 = new javax.swing.JLabel();
        txtNoRoom = new java.awt.TextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tglCheckIn = new java.awt.TextField();
        jLabel13 = new javax.swing.JLabel();
        txtJumlahPay = new java.awt.TextField();
        clear = new javax.swing.JButton();
        tglCheckOut = new java.awt.TextField();
        jLabel14 = new javax.swing.JLabel();
        txtHarga = new java.awt.TextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataGT = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        C_CheckIN = new javax.swing.JButton();
        mangeRoom = new javax.swing.JButton();
        C_CheckOut = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No Identitas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 104, -1, 24));

        txtID.setText("...");
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 138, 204, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nama Lengkap");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 104, -1, 24));

        txtNo.setText("...");
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 210, 205, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nomer Hp");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 168, -1, 24));

        btnCheckOut.setBackground(new java.awt.Color(255, 0, 0));
        btnCheckOut.setText("Check Out!");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 254, 98, -1));

        txtNama.setText("...");
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 138, 205, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Hari");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 176, -1, 24));

        txtLamaInap.setText("...");
        jPanel1.add(txtLamaInap, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 210, 205, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nomor Reservasi");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 24, -1, 30));
        jPanel1.add(txtNoRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 30, 177, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Harga");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 176, -1, 24));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Check In (Today)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 104, -1, 24));

        tglCheckIn.setText("...");
        jPanel1.add(tglCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 138, 205, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Jumlah Bayar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 168, -1, 24));

        txtJumlahPay.setText("...");
        jPanel1.add(txtJumlahPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 210, 205, -1));

        clear.setBackground(new java.awt.Color(255, 255, 0));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 254, 98, 20));

        tglCheckOut.setText("...");
        tglCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglCheckOutActionPerformed(evt);
            }
        });
        jPanel1.add(tglCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 138, 205, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Check Out");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 104, -1, 24));

        txtHarga.setText("...");
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 205, -1));

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 27, 71, -1));

        tabelDataGT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "No Hp", "Negara", "Alamat", "Gender", "Tanggal Check In", "No Kamar", "Type ", "Total Bayar"
            }
        ));
        jScrollPane1.setViewportView(tabelDataGT);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 283, 975, 141));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/all pages background.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 86, -1, 490));

        C_CheckIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/Customer Registration & Check IN.png"))); // NOI18N
        C_CheckIN.setText("Customer Check-In");
        C_CheckIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_CheckINActionPerformed(evt);
            }
        });
        getContentPane().add(C_CheckIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 11, 145, 43));

        mangeRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/manage room.png"))); // NOI18N
        mangeRoom.setText("Manage Room");
        mangeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangeRoomActionPerformed(evt);
            }
        });
        getContentPane().add(mangeRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 11, 145, 43));

        C_CheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/Customer Check Out.png"))); // NOI18N
        C_CheckOut.setText("Customer Check-Out");
        getContentPane().add(C_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 11, 145, 43));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/exit.png"))); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(977, 11, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/6479339.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 150, 60));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/logout.png"))); // NOI18N
        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 11, 100, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hotel Images & Icon/home.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed

        ReservasiRepo.deleteById(Integer.valueOf(txtNoRoom.getText()));
        updateTable();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        //Method Mencari Data berdasrkan Id Reservasi
        Reservasi reservasi = ReservasiRepo.getById(Integer.valueOf(txtNoRoom.getText()));
        Guest guest = GuestRepo.getById(reservasi.getGuestId());
        Room room = RoomRepo.getById(reservasi.getRoomId());
        
        txtNama.setText(guest.getName());
        tglCheckIn.setText(reservasi.getTglCheckin());
        txtLamaInap.setText(Integer.toString(reservasi.getTotalHari()));
        txtHarga.setText(Double.toString(room.getPrice()));
        txtJumlahPay.setText(Double.toString(reservasi.getJumlahBayar()));
        txtNo.setText(Integer.toString(guest.getContact()));
        txtID.setText(Integer.toString(guest.getId()));
        tglCheckOut.setText(reservasi.getTglCheckout());
    }//GEN-LAST:event_btnSearchActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int keluar = JOptionPane.showConfirmDialog(null, "Anda akan LogOut?", "Question", JOptionPane.YES_NO_OPTION);
        if (keluar == 0) {
            Login1 exit = new Login1();
            exit.setVisible(true);
            this.dispose();
        } else {
            return;

        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int kembali = JOptionPane.showConfirmDialog(null, "Anda akan Kembali?", "Question", JOptionPane.YES_NO_OPTION);
        if (kembali == 0) {
            FormReservasi beck = new FormReservasi();
            beck.setVisible(true);
            this.dispose();
        } else {
            return;

        }
    }//GEN-LAST:event_exitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearTextFields();
    }//GEN-LAST:event_clearActionPerformed

    private void mangeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangeRoomActionPerformed
        FormRoom next = new FormRoom();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mangeRoomActionPerformed

    private void C_CheckINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_CheckINActionPerformed
        FormCustomerIn next = new FormCustomerIn();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_C_CheckINActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
//        Reservasi reservasi = ReservasiRepo.getById(Integer.valueOf(txtNoRoom.getText()));
//        Guest guest = GuestRepo.getById(reservasi.getGuestId());
//        Room room = RoomRepo.getById(reservasi.getRoomId());
//        
//        txtNama.setText(guest.getName());
//        tglCheckIn.setText(reservasi.getTglCheckin());
//        txtLamaInap.setText(Integer.toString(reservasi.getTotalHari()));
//        txtHarga.setText(Double.toString(room.getPrice()));
//        txtJumlahPay.setText(Double.toString(reservasi.getJumlahBayar()));
//        txtNo.setText(Integer.toString(guest.getContact()));
//        txtID.setText(Integer.toString(guest.getId()));
//        tglCheckOut.setText(Integer.toString(reservasi.getTotalHari()));
        
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void tglCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromCustomerOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromCustomerOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromCustomerOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromCustomerOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromCustomerOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_CheckIN;
    private javax.swing.JButton C_CheckOut;
    private javax.swing.JButton Logout;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton clear;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mangeRoom;
    private javax.swing.JTable tabelDataGT;
    private java.awt.TextField tglCheckIn;
    private java.awt.TextField tglCheckOut;
    private java.awt.TextField txtHarga;
    private java.awt.TextField txtID;
    private java.awt.TextField txtJumlahPay;
    private java.awt.TextField txtLamaInap;
    private java.awt.TextField txtNama;
    private java.awt.TextField txtNo;
    private java.awt.TextField txtNoRoom;
    // End of variables declaration//GEN-END:variables
}
